name: Build and Push Docker Images to Google Cloud

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REPOSITORY: sistemas-distribuidos

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configurar Docker para Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Construir y subir Gateway
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/gateway:v1 -f Dockerfile.gateway .
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/gateway:v1

      - name: Construir y subir Problema
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/problema:v1 -f Dockerfile.problema .
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/problema:v1

      - name: Construir y subir Queja
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/queja:v1 -f Dockerfile.queja .
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/queja:v1

      - name: Construir y subir Duda
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/duda:v1 -f Dockerfile.duda .
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sistemas-distribuidos/duda:v1
